# -*- coding: utf-8 -*-
"""UAS_ALT_Kelompok 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5PsTinGpEqrAQNBpePx8p6WWR4VX3MC

Nama 1: Saskia Putri Maharani
<br> NPM 1 : 140110210019
<br> Nama 2: Novan Ramadhani Nur Faza
<br> NPM 2 : 140110210020
# Ujian Akhir Semester Aljabar Linear Terapan

## Rantai Markov
"""

from sympy import *
from IPython.display import Math

"""### Definisi fungsi peluang matriks transisi"""

init_printing()
def peluang():
    n = int(input("Masukan ukuran matriks yang di inginkan: "))
    P = zeros(n,n)
    x = zeros(n,1)

    for i in range(0,n):
        for j in range(0,n):
            P[i,j] = str(input(f"Input nilai P[{i+1,j+1}]: "))

    for i in range(0,n):
        x[i] = str(input(f"Input nilai x[{i+1}]: "))

    display(f"Matriks Peluang P dan x(0) awal")
    display(Math(f"P = {latex(P)}"))
    display(Math(f"x(0) = {latex(x)}"))
    return P, x, n

"""### Definisi fungsi peluang pada waktu ke-n"""

def Peluang_n(P, x):
    n = int(input("Peluang keadaaan pada waktu ke-n yang ingin di cari: "))
    m = []
    for i in range(0,n+1):
      m.append(P**i*x)
    for i in range(len(m)):
      print("\n")
      display(Math(f"x({i}) : {latex(m[i])}"))

"""### Definisi fungsi untuk menghitung jumlah setiap kolom"""

def jumlah_kolom(P, n):
  m = int(input("Peluang transisi keberapa yang ingin dicek jumlah setiap kolomnya: "))
  p = P**m
  print(f"\nAkan diperiksa jumlah setiap Kolom pada P ke-{m}")

  for i in range(0,n):
    q = 0
    for j in range(0,n):
      q += P[j,i]

    print(f"\nKolom({i+1}) = {q}")

"""### Definisi fungsi untuk periksa peluang keadaaan tunak"""

def vektor_tunak(P, n):
  m = int(input("Periksa keadaan tunak pada P ke berapa: "))
  P = P**m
  I = eye(n)
  b = zeros(n,1)
  s = 0

  sol, params = (I-P).gauss_jordan_solve(b)

  tau_0 = {tau: 1 for tau in params}
  q = sol.xreplace(tau_0)

  #ubah menjadi peluang
  for i in range(0,n):
    s += q[i]

  s = 1/s

  for i in range(0,n):
    q[i] = (q[i]*s)

  print("Vektor keadaan tunak:")
  display(Math(f"q = {latex(q)}"))

"""### Contoh Penggunaan, dan menyelesaikan latihan"""

P, x, n = peluang()

Peluang_n(P,x)

vektor_tunak(P,n)

jumlah_kolom(P,n)